/* CutFlowX detection engine — generated by `npm run build:panel`. Do not edit. */
"use strict";
var CutFlowXEngine = (() => {
  var __defProp = Object.defineProperty;
  var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
  var __getOwnPropNames = Object.getOwnPropertyNames;
  var __hasOwnProp = Object.prototype.hasOwnProperty;
  var __export = (target, all) => {
    for (var name in all)
      __defProp(target, name, { get: all[name], enumerable: true });
  };
  var __copyProps = (to, from, except, desc) => {
    if (from && typeof from === "object" || typeof from === "function") {
      for (let key of __getOwnPropNames(from))
        if (!__hasOwnProp.call(to, key) && key !== except)
          __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
    }
    return to;
  };
  var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

  // src/panel/engineBundle.ts
  var engineBundle_exports = {};
  __export(engineBundle_exports, {
    DEFAULT_SETTINGS: () => DEFAULT_SETTINGS,
    ENGINE_VERSION: () => ENGINE_VERSION,
    analyzeSilence: () => analyzeSilence,
    describeTimebase: () => describeTimebase,
    formatDiagnostics: () => formatDiagnostics,
    formatTicks: () => formatTicks,
    frameRateFromTicksPerFrame: () => frameRateFromTicksPerFrame,
    keepRanges: () => keepRanges,
    parseWav: () => parseWav,
    selfTest: () => selfTest,
    ticksToFrames: () => ticksToFrames,
    validateCutPlan: () => validateCutPlan
  });

  // src/audio/audioTypes.ts
  var DEFAULT_SETTINGS = {
    thresholdDb: -32,
    minSilenceMs: 500,
    paddingBeforeMs: 80,
    paddingAfterMs: 100
  };
  var DEFAULT_TUNING = {
    windowMs: 20,
    hopMs: 5,
    hysteresisDb: 3,
    mergeGapMs: 50,
    settleDb: 6,
    settleMs: 30,
    floorPercentile: 0.2,
    minFloorMarginDb: 6,
    inaudibleDb: -60,
    roomTonePercentile: 0.05,
    clickIsolationMs: 100,
    minCutMs: 100
  };
  var CutFlowXError = class extends Error {
    constructor(message, detail) {
      super(message);
      this.detail = detail;
      this.name = "CutFlowXError";
    }
  };

  // src/audio/wavReader.ts
  var FORMAT_PCM = 1;
  var FORMAT_FLOAT = 3;
  var FORMAT_EXTENSIBLE = 65534;
  function fourCC(view, offset) {
    return String.fromCharCode(view.getUint8(offset), view.getUint8(offset + 1), view.getUint8(offset + 2), view.getUint8(offset + 3));
  }
  function parseWav(input) {
    const bytes = input instanceof Uint8Array ? input : new Uint8Array(input);
    const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
    const fail = (detail) => {
      throw new CutFlowXError("The extracted audio could not be read.", `WAV: ${detail}`);
    };
    if (bytes.byteLength < 12 || fourCC(view, 0) !== "RIFF" || fourCC(view, 8) !== "WAVE") {
      const isMp3 = bytes.byteLength >= 3 && String.fromCharCode(bytes[0], bytes[1], bytes[2]) === "ID3" || bytes.byteLength >= 2 && bytes[0] === 255 && (bytes[1] & 224) === 224;
      if (isMp3) {
        throw new CutFlowXError(
          "This is an MP3 file. CutFlowX needs WAV audio. In Premiere, export it with Format: Waveform Audio (48 kHz).",
          "MP3 adds encoder delay that would shift every cut; renaming the file to .wav does not convert it"
        );
      }
      fail("not a RIFF/WAVE file");
    }
    let format = -1;
    let channels = 0;
    let sampleRate = 0;
    let bits = 0;
    let dataOffset = -1;
    let dataSize = 0;
    let offset = 12;
    while (offset + 8 <= bytes.byteLength) {
      const id = fourCC(view, offset);
      const size = view.getUint32(offset + 4, true);
      const body = offset + 8;
      if (id === "fmt ") {
        if (size < 16) fail("fmt chunk too small");
        format = view.getUint16(body, true);
        channels = view.getUint16(body + 2, true);
        sampleRate = view.getUint32(body + 4, true);
        bits = view.getUint16(body + 14, true);
        if (format === FORMAT_EXTENSIBLE) {
          if (size < 40) fail("extensible fmt chunk too small");
          format = view.getUint16(body + 24, true);
        }
      } else if (id === "data") {
        dataOffset = body;
        const remaining = bytes.byteLength - body;
        dataSize = size === 0 || size === 4294967295 || size > remaining ? remaining : size;
        break;
      }
      offset = body + size + size % 2;
    }
    if (format < 0) fail("missing fmt chunk");
    if (dataOffset < 0) fail("missing data chunk");
    if (channels < 1) fail("zero channels");
    if (sampleRate < 1) fail("zero sample rate");
    const bytesPerSample = bits / 8;
    const supported = format === FORMAT_PCM && [8, 16, 24, 32].includes(bits) || format === FORMAT_FLOAT && (bits === 32 || bits === 64);
    if (!supported) fail(`unsupported format ${format} at ${bits}-bit`);
    const frameBytes = bytesPerSample * channels;
    const frames = Math.floor(dataSize / frameBytes);
    const out = Array.from({ length: channels }, () => new Float32Array(frames));
    for (let f = 0; f < frames; f++) {
      for (let c = 0; c < channels; c++) {
        const p = dataOffset + f * frameBytes + c * bytesPerSample;
        let v;
        if (format === FORMAT_FLOAT) {
          v = bits === 32 ? view.getFloat32(p, true) : view.getFloat64(p, true);
        } else if (bits === 8) {
          v = (view.getUint8(p) - 128) / 128;
        } else if (bits === 16) {
          v = view.getInt16(p, true) / 32768;
        } else if (bits === 24) {
          const raw = view.getUint8(p) | view.getUint8(p + 1) << 8 | view.getUint8(p + 2) << 16;
          v = (raw << 8 >> 8) / 8388608;
        } else {
          v = view.getInt32(p, true) / 2147483648;
        }
        out[c][f] = v;
      }
    }
    return { sampleRate, channels: out };
  }

  // src/premiere/timecode.ts
  var TICKS_PER_SECOND = 254016000000n;
  function gcd(a, b) {
    while (b !== 0n) [a, b] = [b, a % b];
    return a < 0n ? -a : a;
  }
  function assertValidRate(rate) {
    if (!Number.isInteger(rate.num) || !Number.isInteger(rate.den) || rate.num <= 0 || rate.den <= 0) {
      throw new RangeError(`Invalid frame rate ${rate.num}/${rate.den}`);
    }
  }
  function ticksPerFrame(rate) {
    assertValidRate(rate);
    const numerator = TICKS_PER_SECOND * BigInt(rate.den);
    const num = BigInt(rate.num);
    if (numerator % num !== 0n) {
      throw new RangeError(`Frame rate ${rate.num}/${rate.den} has no integer tick duration`);
    }
    return numerator / num;
  }
  function frameRateFromTicksPerFrame(tpf) {
    const t = BigInt(tpf);
    if (t <= 0n) throw new RangeError(`Invalid timebase ${String(tpf)} ticks/frame`);
    const g = gcd(TICKS_PER_SECOND, t);
    const num = TICKS_PER_SECOND / g;
    const den = t / g;
    if (num > BigInt(Number.MAX_SAFE_INTEGER) || den > BigInt(Number.MAX_SAFE_INTEGER)) {
      throw new RangeError(`Timebase ${String(tpf)} is not a representable frame rate`);
    }
    return { num: Number(num), den: Number(den) };
  }
  function assertSampleArgs(sample, sampleRate) {
    if (!Number.isSafeInteger(sample) || sample < 0) throw new RangeError(`Invalid sample index ${sample}`);
    if (!Number.isSafeInteger(sampleRate) || sampleRate <= 0) throw new RangeError(`Invalid sample rate ${sampleRate}`);
  }
  function sampleToFrameFloor(sample, sampleRate, rate) {
    assertSampleArgs(sample, sampleRate);
    assertValidRate(rate);
    const q = BigInt(sample) * BigInt(rate.num) / (BigInt(sampleRate) * BigInt(rate.den));
    return Number(q);
  }
  function sampleToFrameCeil(sample, sampleRate, rate) {
    assertSampleArgs(sample, sampleRate);
    assertValidRate(rate);
    const n = BigInt(sample) * BigInt(rate.num);
    const d = BigInt(sampleRate) * BigInt(rate.den);
    return Number((n + d - 1n) / d);
  }
  function frameToTicks(frame, rate) {
    if (!Number.isSafeInteger(frame) || frame < 0) throw new RangeError(`Invalid frame ${frame}`);
    return BigInt(frame) * ticksPerFrame(rate);
  }
  function formatClock(sample, sampleRate) {
    const totalMs = Math.floor(sample * 1e3 / sampleRate);
    const ms = totalMs % 1e3;
    const totalSec = Math.floor(totalMs / 1e3);
    const s = totalSec % 60;
    const m = Math.floor(totalSec / 60) % 60;
    const h = Math.floor(totalSec / 3600);
    const pad = (v, w = 2) => String(v).padStart(w, "0");
    return `${pad(h)}:${pad(m)}:${pad(s)}.${pad(ms, 3)}`;
  }

  // src/cutting/diagnostics.ts
  function formatDiagnostics(result, audioSource = "(unspecified)") {
    const sr = result.sampleRate;
    const range = (r) => `${formatClock(r.start, sr)} \u2192 ${formatClock(r.end, sr)}`;
    const fps = result.frameRate.num / result.frameRate.den;
    const s = result.settings;
    const lines = [
      `Audio source:      ${audioSource}`,
      `Duration:          ${formatClock(result.totalSamples, sr)} (${result.totalSamples} samples)`,
      `Sample rate:       ${sr} Hz`,
      `Channels:          ${result.channels}`,
      `Threshold:         ${s.thresholdDb} dB`,
      `Minimum silence:   ${s.minSilenceMs} ms`,
      `Padding before:    ${s.paddingBeforeMs} ms`,
      `Padding after:     ${s.paddingAfterMs} ms`,
      `Timeline edges:    start ${result.edges.startsAtTimelineStart ? "yes (no padding)" : "no"}, end ${result.edges.endsAtTimelineEnd ? "yes (no padding)" : "no"}`,
      `Sequence FPS:      ${fps.toFixed(3)} (${result.frameRate.num}/${result.frameRate.den})`,
      `Frame duration:    ${result.ticksPerFrame} ticks`,
      `Raw silence runs:  ${result.rawRegionCount}`,
      `Final cut regions: ${result.regions.length}`,
      `Dropped:           ${result.dropped.length}`,
      ""
    ];
    for (const r of result.regions) {
      lines.push(
        `#${r.index + 1}`,
        `  Detected:  ${range(r.detected)}`,
        `  Refined:   ${range(r.refined)}   (floor ${r.floorDb.toFixed(1)} dB)`,
        `  Padded:    ${range(r.padded)}`,
        `  Frames:    ${r.startFrame} \u2192 ${r.endFrame}   (${r.endFrame - r.startFrame} frames removed)`,
        `  Ticks:     ${r.startTicks} \u2192 ${r.endTicks}`
      );
    }
    const len = (r) => `${Math.round((r.end - r.start) * 1e3 / sr)} ms`;
    for (const d of result.dropped) {
      const core = d.refined ? `, quiet core ${len(d.refined)}` : "";
      const floor = d.floorDb !== void 0 ? `, floor ${d.floorDb.toFixed(0)} dB` : "";
      lines.push(`dropped  ${range(d.detected)}  (${len(d.detected)}${core}${floor})  \u2014 ${d.reason}`);
    }
    return lines.join("\n");
  }

  // src/cutting/cutValidation.ts
  function validateCutPlan(result) {
    let previousEnd = 0;
    for (const r of result.regions) {
      const where = `region #${r.index + 1} (frames ${r.startFrame}\u2013${r.endFrame})`;
      if (!Number.isSafeInteger(r.startFrame) || !Number.isSafeInteger(r.endFrame)) {
        throw new CutFlowXError("The cut plan is invalid.", `${where}: non-integer frame`);
      }
      if (r.startFrame < 0 || r.endFrame > result.totalFrames) {
        throw new CutFlowXError("The cut plan is invalid.", `${where}: outside 0\u2013${result.totalFrames}`);
      }
      if (r.endFrame <= r.startFrame) {
        throw new CutFlowXError("The cut plan is invalid.", `${where}: empty region`);
      }
      if (r.startFrame < previousEnd) {
        throw new CutFlowXError("The cut plan is invalid.", `${where}: overlaps or is out of order`);
      }
      previousEnd = r.endFrame;
    }
    return result.regions.map(({ startFrame, endFrame }) => ({ startFrame, endFrame }));
  }
  function keepRanges(result) {
    const cuts = validateCutPlan(result);
    const keeps = [];
    let cursor = 0;
    for (const c of cuts) {
      if (c.startFrame > cursor) keeps.push({ startFrame: cursor, endFrame: c.startFrame });
      cursor = c.endFrame;
    }
    if (cursor < result.totalFrames) keeps.push({ startFrame: cursor, endFrame: result.totalFrames });
    return keeps;
  }

  // src/audio/analyzer.ts
  var DB_FLOOR = -120;
  var DIGITAL_SILENCE_DB = -110;
  function estimateRoomTone(db, tuning) {
    const live = Array.from(db).filter((v) => v > DIGITAL_SILENCE_DB).sort((a, b) => a - b);
    if (live.length === 0) return DB_FLOOR;
    return live[Math.floor((live.length - 1) * tuning.roomTonePercentile)];
  }
  function validateAudio(audio) {
    if (!Number.isSafeInteger(audio.sampleRate) || audio.sampleRate <= 0) {
      throw new CutFlowXError("The audio has an invalid sample rate.", `sampleRate=${audio.sampleRate}`);
    }
    const first = audio.channels[0];
    if (!first) throw new CutFlowXError("No audio found to analyze.", "channels=0");
    for (const ch of audio.channels) {
      if (ch.length !== first.length) {
        throw new CutFlowXError("The audio channels have different lengths.", "invalid extraction");
      }
    }
    if (first.length === 0) throw new CutFlowXError("The audio is empty.", "samples=0");
    return first.length;
  }
  function computeLevels(audio, tuning) {
    const total = validateAudio(audio);
    const hop = Math.max(1, Math.round(audio.sampleRate * tuning.hopMs / 1e3));
    const blocksPerWindow = Math.max(1, Math.round(tuning.windowMs / tuning.hopMs));
    const windowSamples = hop * blocksPerWindow;
    const blockCount = Math.ceil(total / hop);
    const blockSums = audio.channels.map((ch) => {
      const sums = new Float64Array(blockCount);
      for (let b = 0; b < blockCount; b++) {
        const end = Math.min(total, (b + 1) * hop);
        let acc = 0;
        for (let i = b * hop; i < end; i++) {
          const v = ch[i];
          acc += v * v;
        }
        sums[b] = acc;
      }
      return sums;
    });
    const db = new Float32Array(blockCount);
    for (let k = 0; k < blockCount; k++) {
      const lastBlock = Math.min(blockCount, k + blocksPerWindow);
      const len = Math.min(total, k * hop + windowSamples) - k * hop;
      let loudestMeanSquare = 0;
      for (const sums of blockSums) {
        let acc = 0;
        for (let b = k; b < lastBlock; b++) acc += sums[b];
        loudestMeanSquare = Math.max(loudestMeanSquare, acc / len);
      }
      db[k] = loudestMeanSquare > 0 ? Math.max(DB_FLOOR, 10 * Math.log10(loudestMeanSquare)) : DB_FLOOR;
    }
    return { sampleRate: audio.sampleRate, hopSamples: hop, windowSamples, totalSamples: total, db, roomToneDb: estimateRoomTone(db, tuning) };
  }

  // src/audio/boundaryRefiner.ts
  function refineRun(run, levels, thresholdDb, tuning) {
    const db = levels.db;
    const values = Array.from(db.subarray(run.first, run.last + 1)).sort((a, b) => a - b);
    const floorDb = values[Math.floor((values.length - 1) * tuning.floorPercentile)];
    if (floorDb > thresholdDb - tuning.minFloorMarginDb) return { ok: false, reason: "no-clear-silence", floorDb };
    const base = Math.min(floorDb, levels.roomToneDb);
    const settleDb = Math.min(thresholdDb - tuning.minFloorMarginDb, Math.max(base + tuning.settleDb, tuning.inaudibleDb));
    const settleWindows = Math.max(1, Math.round(tuning.settleMs / tuning.hopMs));
    let first = -1;
    let streak = 0;
    for (let k = run.first; k <= run.last; k++) {
      streak = db[k] <= settleDb ? streak + 1 : 0;
      if (streak >= settleWindows) {
        first = k - settleWindows + 1;
        break;
      }
    }
    if (first < 0) return { ok: false, reason: "no-stable-floor", floorDb };
    let last = -1;
    streak = 0;
    for (let k = run.last; k >= first; k--) {
      streak = db[k] <= settleDb ? streak + 1 : 0;
      if (streak >= settleWindows) {
        last = k + settleWindows - 1;
        break;
      }
    }
    if (last < 0) return { ok: false, reason: "no-stable-floor", floorDb };
    return { ok: true, run: { first, last }, floorDb, settleDb };
  }
  function findInteriorSound(run, levels, settleDb, tuning) {
    const maxBurstWindows = Math.floor(tuning.mergeGapMs / tuning.hopMs);
    const isolationWindows = Math.ceil(tuning.clickIsolationMs / tuning.hopMs);
    const bursts = [];
    let start = -1;
    for (let k = run.first; k <= run.last + 1; k++) {
      const loud = k <= run.last && levels.db[k] > settleDb;
      if (loud && start < 0) start = k;
      if (!loud && start >= 0) {
        bursts.push({ first: start, last: k - 1 });
        start = -1;
      }
    }
    let longest = null;
    bursts.forEach((b, i) => {
      const quietBefore = b.first - (i > 0 ? bursts[i - 1].last + 1 : run.first);
      const quietAfter = (i < bursts.length - 1 ? bursts[i + 1].first - 1 : run.last) - b.last;
      const isClick = b.last - b.first + 1 <= maxBurstWindows && quietBefore >= isolationWindows && quietAfter >= isolationWindows;
      if (!isClick && (!longest || b.last - b.first > longest.last - longest.first)) longest = b;
    });
    return longest;
  }

  // src/audio/silenceDetector.ts
  function detectQuietRuns(levels, thresholdDb, tuning) {
    const exitDb = thresholdDb + tuning.hysteresisDb;
    const runs = [];
    let start = -1;
    let lastQuiet = -1;
    for (let k = 0; k < levels.db.length; k++) {
      const v = levels.db[k];
      if (start < 0) {
        if (v <= thresholdDb) {
          start = k;
          lastQuiet = k;
        }
      } else if (v > exitDb) {
        runs.push({ first: start, last: lastQuiet });
        start = -1;
      } else if (v <= thresholdDb) {
        lastQuiet = k;
      }
    }
    if (start >= 0) runs.push({ first: start, last: lastQuiet });
    return runs;
  }
  function mergeCloseRuns(runs, tuning) {
    const maxGapWindows = Math.floor(tuning.mergeGapMs / tuning.hopMs);
    const merged = [];
    for (const run of runs) {
      const prev = merged[merged.length - 1];
      if (prev && run.first - prev.last - 1 <= maxGapWindows) {
        merged[merged.length - 1] = { first: prev.first, last: run.last };
      } else {
        merged.push(run);
      }
    }
    return merged;
  }
  function runDetectedSpan(run, levels) {
    const start = run.first * levels.hopSamples;
    const end = Math.min(levels.totalSamples, run.last * levels.hopSamples + levels.windowSamples);
    return { start, end };
  }
  function runSafeRange(run, levels) {
    const h = levels.hopSamples;
    const n = levels.totalSamples;
    const lastIndex = levels.db.length - 1;
    const start = run.first === 0 ? 0 : Math.min(n, (run.first - 1) * h + levels.windowSamples);
    const end = run.last === lastIndex ? n : Math.min(n, (run.last + 1) * h);
    return { start, end: Math.max(start, end) };
  }

  // src/engine.ts
  var NO_EDGES = { startsAtTimelineStart: false, endsAtTimelineEnd: false };
  function validateSettings(s) {
    const check = (ok, message) => {
      if (!ok) throw new CutFlowXError(message);
    };
    check(Number.isFinite(s.thresholdDb) && s.thresholdDb >= -90 && s.thresholdDb <= -6, "Threshold must be between -90 dB and -6 dB.");
    check(Number.isFinite(s.minSilenceMs) && s.minSilenceMs >= 50 && s.minSilenceMs <= 6e4, "Minimum silence must be between 50 ms and 60 s.");
    check(Number.isFinite(s.paddingBeforeMs) && s.paddingBeforeMs >= 0 && s.paddingBeforeMs <= 2e3, "Padding before must be between 0 and 2000 ms.");
    check(Number.isFinite(s.paddingAfterMs) && s.paddingAfterMs >= 0 && s.paddingAfterMs <= 2e3, "Padding after must be between 0 and 2000 ms.");
  }
  var msToSamples = (ms, sampleRate) => Math.round(ms * sampleRate / 1e3);
  function analyzeSilence(audio, settings, frameRate, tuning = DEFAULT_TUNING, edges = NO_EDGES) {
    validateSettings(settings);
    if (tuning.windowMs % tuning.hopMs !== 0) throw new CutFlowXError("Internal tuning error.", "windowMs must be a multiple of hopMs");
    const tpf = ticksPerFrame(frameRate);
    const levels = computeLevels(audio, tuning);
    const sr = levels.sampleRate;
    const n = levels.totalSamples;
    const totalFrames = sampleToFrameFloor(n, sr, frameRate);
    const rawRuns = detectQuietRuns(levels, settings.thresholdDb, tuning);
    const runs = mergeCloseRuns(rawRuns, tuning);
    const minSamples = msToSamples(settings.minSilenceMs, sr);
    const padBefore = msToSamples(settings.paddingBeforeMs, sr);
    const padAfter = msToSamples(settings.paddingAfterMs, sr);
    const pieces = [];
    const dropped = [];
    for (const run of runs) {
      const detected = runDetectedSpan(run, levels);
      if (detected.end - detected.start < minSamples) {
        dropped.push({ detected, reason: "shorter-than-minimum" });
        continue;
      }
      const queue = [run];
      while (queue.length > 0) {
        const piece = queue.pop();
        const isSplitPiece = piece !== run;
        const refinedOutcome = refineRun(piece, levels, settings.thresholdDb, tuning);
        const spanForReport = isSplitPiece ? runDetectedSpan(piece, levels) : detected;
        if (!refinedOutcome.ok) {
          dropped.push({ detected: spanForReport, reason: isSplitPiece ? "split-by-interior-sound" : refinedOutcome.reason, floorDb: refinedOutcome.floorDb });
          continue;
        }
        const burst = findInteriorSound(refinedOutcome.run, levels, refinedOutcome.settleDb, tuning);
        if (burst) {
          if (burst.first - 1 >= refinedOutcome.run.first) queue.push({ first: refinedOutcome.run.first, last: burst.first - 1 });
          if (burst.last + 1 <= refinedOutcome.run.last) queue.push({ first: burst.last + 1, last: refinedOutcome.run.last });
          continue;
        }
        const floorDb = refinedOutcome.floorDb;
        const refined = runSafeRange(refinedOutcome.run, levels);
        const refinedSpan = runDetectedSpan(refinedOutcome.run, levels);
        const tooShort = isSplitPiece ? "split-by-interior-sound" : "quiet-core-shorter-than-minimum";
        if (refinedSpan.end - refinedSpan.start < minSamples) {
          dropped.push({ detected: spanForReport, reason: tooShort, refined, floorDb });
          continue;
        }
        const noWordBefore = edges.startsAtTimelineStart && refined.start === 0;
        const noWordAfter = edges.endsAtTimelineEnd && refined.end === n;
        const padded = {
          start: refined.start + (noWordBefore ? 0 : padBefore),
          end: refined.end - (noWordAfter ? 0 : padAfter)
        };
        if (padded.end <= padded.start) {
          dropped.push({ detected: spanForReport, reason: "consumed-by-padding", refined, floorDb });
          continue;
        }
        const startFrame = sampleToFrameCeil(padded.start, sr, frameRate);
        const endFrame = Math.min(totalFrames, sampleToFrameFloor(padded.end, sr, frameRate));
        if (endFrame <= startFrame) {
          dropped.push({ detected: spanForReport, reason: "shorter-than-one-frame", refined, floorDb });
          continue;
        }
        if ((endFrame - startFrame) * frameRate.den * 1e3 / frameRate.num < tuning.minCutMs) {
          dropped.push({ detected: spanForReport, reason: "cut-too-short", refined, floorDb });
          continue;
        }
        pieces.push({
          detected,
          refined,
          padded,
          startFrame,
          endFrame,
          startTicks: frameToTicks(startFrame, frameRate),
          endTicks: frameToTicks(endFrame, frameRate),
          floorDb
        });
      }
    }
    const regions = pieces.sort((x, y) => x.startFrame - y.startFrame).map((p, index) => ({ index, ...p }));
    const uniquePauses = new Map(regions.map((r) => [r.detected.start, r.detected.end - r.detected.start]));
    const detectedSilenceSec = [...uniquePauses.values()].reduce((a, b) => a + b, 0) / sr;
    const removedFrames = regions.reduce((acc, r) => acc + (r.endFrame - r.startFrame), 0);
    return {
      sampleRate: sr,
      channels: audio.channels.length,
      totalSamples: n,
      totalFrames,
      frameRate,
      ticksPerFrame: tpf,
      settings,
      tuning,
      edges,
      rawRegionCount: rawRuns.length,
      regions,
      dropped: dropped.sort((x, y) => x.detected.start - y.detected.start),
      detectedSilenceSec,
      removableSec: removedFrames * frameRate.den / frameRate.num
    };
  }

  // src/panel/engineBundle.ts
  var ENGINE_VERSION = "0.4.0";
  function describeTimebase(timebaseTicks) {
    const rate = frameRateFromTicksPerFrame(timebaseTicks);
    const fps = rate.num / rate.den;
    const label = rate.den === 1 ? `${rate.num} fps` : `${fps.toFixed(3).replace(/0+$/, "").replace(/\.$/, "")} fps`;
    return { fps, label, rate, ticksPerFrame: ticksPerFrame(rate).toString() };
  }
  function ticksToFrames(ticks, timebaseTicks) {
    return Number(BigInt(ticks) / BigInt(timebaseTicks));
  }
  function formatTicks(ticks) {
    const t = BigInt(ticks);
    if (t < 0n) return "-" + formatTicks((-t).toString());
    const ms = Number(t * 1000n / TICKS_PER_SECOND);
    const pad = (v, w = 2) => String(v).padStart(w, "0");
    return `${pad(Math.floor(ms / 36e5))}:${pad(Math.floor(ms / 6e4) % 60)}:${pad(Math.floor(ms / 1e3) % 60)}.${pad(ms % 1e3, 3)}`;
  }
  function selfTest() {
    try {
      const sr = 48e3;
      const n = sr * 3.5;
      const ch = new Float32Array(n);
      let seed = 12345;
      const rnd = () => (seed = seed * 1103515245 + 12345 >>> 0) / 4294967296 * 2 - 1;
      for (let i = 0; i < n; i++) {
        const t = i / sr;
        const loud = t < 1 || t >= 2.5;
        ch[i] = rnd() * (loud ? 0.3 : 3e-4);
      }
      const audio = { sampleRate: sr, channels: [ch] };
      const r = analyzeSilence(audio, DEFAULT_SETTINGS, { num: 3e4, den: 1001 });
      const c = r.regions[0];
      const ok = r.regions.length === 1 && !!c && c.startFrame >= 30 && c.endFrame <= 75 && c.endFrame > c.startFrame;
      return ok ? { ok: true, message: `1 silence found at frames ${c.startFrame}\u2013${c.endFrame}` } : { ok: false, message: `Expected 1 silence inside frames 30\u201375, got ${r.regions.length}` };
    } catch (e) {
      return { ok: false, message: e instanceof Error ? e.message : String(e) };
    }
  }
  return __toCommonJS(engineBundle_exports);
})();
